### ISSUE TITLE
Bug: can't download vocabulary list

### ISSUE THREAD

**Issue by jdestgermain** [CharaChorder/DeviceManager#126]
+page.svelte:186  Uncaught ReferenceError: plainPhrase is not defined
    at +page.svelte:186:9
    at Array.map (<anonymous>)
    at HTMLButtonElement.L (+page.svelte:185:15)

**Comment by sakura-rip** [comment]
<img width="603" alt="image" src="https://github.com/user-attachments/assets/697ab4ff-3ff1-46b5-a538-e4ae3c0ede95">
<img width="636" alt="image" src="https://github.com/user-attachments/assets/25b5fa94-129e-40fd-bc86-b2fb859f44bd">

This can be easily corrected by adapting this change.
Output is perfect as expected!

**Comment by sakura-rip** [comment]
@jdestgermain 
Thanks for the feedback. I was mistaken.
I have added a simple fix

<img width="652" alt="image" src="https://github.com/user-attachments/assets/fcd9ec81-dd1c-48e7-a319-278d638e77aa">
