### ISSUE TITLE
Split site into stable and dev version

### ISSUE THREAD

**Issue by Theaninova** [CharaChorder/DeviceManager#37]
There should be a stable version and one in active development (and possibly `beta`?)
* https://manager.charachorder.com for whatever is the latest commit on the master branch
* https://dev.manager.charachorder.com for whatever is the latest commit on the develop branch
* Any other versions that are in-between

**Comment by Raymo111** [comment]
@Theaninova this can't be done with our current workflow (GitHub pages only supports one site per repo). If this is important, we could possibly switch over to CloudFlare pages instead.

**Comment by Theaninova** [comment]
> @Theaninova this can't be done with our current workflow (GitHub pages only supports one site per repo). If this is important, we could possibly switch over to CloudFlare pages instead.

I think it would definitely be beneficial. Having a dev version allows us to push quick fixes within minutes for people without running the risk of having pushed changes that break stuff for every other user.

**Comment by Raymo111** [comment]
https://dev.manager.charachorder.com/ Done!
