### ISSUE TITLE
Double Layout UI

### ISSUE THREAD

**Issue by duianto** [CharaChorder/DeviceManager#55]
The layout UI appears twice when the terminal is open and the Layout button is clicked.
- Open the Terminal
- Click on the top middle Layout button

### Expected
The layout UI should only appear once.

### Workaround
Clicking on the Layout button again removes the duplicate.

### Observed

![msedge_s0flYe0O2C](https://github.com/CharaChorder/DeviceManager/assets/13420573/b89ee779-063f-4f19-8a57-e57ea35f0ee2)

**Comment by Theaninova** [comment]
Related to https://github.com/CharaChorder/DeviceManager/issues/23
