### ISSUE TITLE
A chord letter overlaps the page bottom text: File an issue

### ISSUE THREAD

**Issue by duianto** [CharaChorder/DeviceManager#56]
In the Chords section. 
At the beginning of the last visible chord.
The first chord letter overlaps the text `File an issue` at the bottom of the page, at some browser window heights.

### Reproduction steps
- Open the Chords section
- Drag the browser's top edge down or up to change the window height.
And keep looking at the beginning of the last visible chord.

### Expected
The last visible chord should be hidden above the bottom row of the page.

### Observed

The beginning of the last visible chord overlaps the `File an issue` text.

https://github.com/CharaChorder/DeviceManager/assets/13420573/690ffc3f-4848-48fb-a003-69baacb1362e

**Comment by Theaninova** [comment]
Hmm yeah we definitely need a more permanent solution for this... I'm not entirely happy with its current state especially with some of the future things coming to the chord list...
