### ISSUE TITLE
On first connect: `TypeError: object null is not iterable`

### ISSUE THREAD

**Issue by agnoster** [CharaChorder/DeviceManager#95]
Ordered a CharaCorder a long time ago, finally thought I'd give it a go - first time connecting to the device manager immediately after selecting the device, I get an alert:

![Screenshot 2024-02-16 at 11 03 11](https://github.com/CharaChorder/DeviceManager/assets/15210/c7b104cb-1a1c-4cfd-82c4-5db0cb3533ec)
![Screenshot 2024-02-16 at 11 03 15](https://github.com/CharaChorder/DeviceManager/assets/15210/fd43624f-c99c-4b34-8779-56760ab5da0d)

I did a little digging and it looks _likely_ that this is due to constructing a SemVer from a string that doesn't match the regex, possibly because my firmware is so old? It would be nice to have some kind of graceful fallback for devices like mine, or some easy path to upgrade to a newer firmware, but afaict the way to do that is... using the DeviceManager. Catch-22 🤣

**Comment by Theaninova** [comment]
Yeah I'm not sure what made me think requiring the version string to match a specific regex would be a good idea

**Comment by FipsiDipsi** [comment]
how can i update my charachorder if I am not able to connect device manager?

**Comment by Shupsta** [comment]
I'm having the same problem, I  cant connect how should I update?

**Comment by FipsiDipsi** [comment]
It actually works to do it as per this tutorial: 
 https://www.charachorder.com/pages/migrating-to-ccos

There is a link for an older charachorder manager that you will be able to connect to and update it as per the steps in the above link. 

This is the website where you can still connect: 
https://launchpad.charachorder.com/#/manager

**Comment by Shupsta** [comment]
@FipsiDipsi That worked perfect, all updated. Thank you for the help.

**Comment by Theaninova** [comment]
Should hopefully be solved now, the pre-ccos and other things will be tracked in https://github.com/CharaChorder/DeviceManager/issues/99
