### ISSUE TITLE
LED settings on CharaChorder Lite don't work

### ISSUE THREAD

**Issue by jdestgermain** [CharaChorder/DeviceManager#97]
Remove reactive keys
Brightness should be working, but it isn't, takes values from 0 to 50 and should set 0x81 in the serial API 

Color could be added, 0x82 and the values for colors are:
0 is white
1 is red
2 is orange
3 is yellow
4 is lime
5 is green

7 is cyan

9 is blue
10 is violet
11 is pink

13 is multicolor

**Comment by Theaninova** [comment]
@jdestgermain Can you check if this works on the dev site? https://dev.manager.charachorder.com/config/settings/

**Comment by Theaninova** [comment]
@jdestgermain Okay, try again
